### PR TITLE
Updates for Julia 0.7 and 1.0

### PR DESCRIPTION
**Pull request by ararslan**
Summary of changes:
* Add 0.7 and 1.0 to the Travis matrix
* Use the default Travis script
* Remove dependency on Nullables
* Use `Union`s instead of `Nullable`s to represent optional values

### CODE REVIEW

**Comment by iamed2** [comment]
Can you rebase and remove the CI changes? I've fixed those separately, including stuff you missed

**Comment by iamed2** [comment]
You can't remove nullables until you do a performance comparison and match the performance gains in the README

**Comment by ararslan** [comment]
Here's a comparison on Julia 1.0, using the examples in the README:
```
julia> t1 = @benchmark for i = 1:10 func1(3, i % 2) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     212.066 μs (0.00% GC)
  median time:      214.093 μs (0.00% GC)
  mean time:        219.881 μs (0.00% GC)
  maximum time:     1.165 ms (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> t2 = @benchmark for i = 1:10 new1(3, i % 2) end # Nullable approach
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.826 ns (0.00% GC)
  median time:      1.978 ns (0.00% GC)
  mean time:        2.014 ns (0.00% GC)
  maximum time:     42.855 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

julia> t3 = @benchmark for i = 1:10 new2(3, i % 2) end # Union approach
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.827 ns (0.00% GC)
  median time:      1.986 ns (0.00% GC)
  mean time:        2.018 ns (0.00% GC)
  maximum time:     29.482 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
```
And without the error condition triggered:
```
julia> t1 = @benchmark for i = 1:10 func1(3, 1) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     168.641 ns (0.00% GC)
  median time:      173.775 ns (0.00% GC)
  mean time:        180.354 ns (0.00% GC)
  maximum time:     422.735 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     746

julia> t2 = @benchmark for i = 1:10 new1(3, 1) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.826 ns (0.00% GC)
  median time:      1.978 ns (0.00% GC)
  mean time:        2.002 ns (0.00% GC)
  maximum time:     42.515 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

julia> t3 = @benchmark for i = 1:10 new2(3, 1) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.827 ns (0.00% GC)
  median time:      1.979 ns (0.00% GC)
  mean time:        1.993 ns (0.00% GC)
  maximum time:     16.808 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
```
So on 1.0, the performance is exactly equivalent on average, with very significant improvement for maximum time using `Union`s.

Now, unsurprisingly the news isn't so peachy on 0.6.
```
julia> t1 = @benchmark for i = 1:10 func1(3, i % 2) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     332.067 μs (0.00% GC)
  median time:      335.471 μs (0.00% GC)
  mean time:        342.921 μs (0.00% GC)
  maximum time:     740.108 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> t2 = @benchmark for i = 1:10 new1(3, i % 2) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     107.891 ns (0.00% GC)
  median time:      108.277 ns (0.00% GC)
  mean time:        110.710 ns (0.00% GC)
  maximum time:     323.416 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     930

julia> t3 = @benchmark for i = 1:10 new2(3, i % 2) end
BenchmarkTools.Trial:
  memory estimate:  400 bytes
  allocs estimate:  15
  --------------
  minimum time:     222.142 ns (0.00% GC)
  median time:      228.458 ns (0.00% GC)
  mean time:        253.854 ns (8.10% GC)
  maximum time:     3.156 μs (89.71% GC)
  --------------
  samples:          10000
  evals/sample:     487
```
So there's still an improvement over `try` when using `Union`s, but it's still significantly slower than `Nullable` on 0.6. And when the error condition isn't triggered:
```
julia> t1 = @benchmark for i = 1:10 func1(3, 1) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     236.365 ns (0.00% GC)
  median time:      237.593 ns (0.00% GC)
  mean time:        244.379 ns (0.00% GC)
  maximum time:     606.040 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     425

julia> t2 = @benchmark for i = 1:10 new1(3, 1) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     159.883 ns (0.00% GC)
  median time:      160.176 ns (0.00% GC)
  mean time:        167.540 ns (0.00% GC)
  maximum time:     3.382 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     788

julia> t3 = @benchmark for i = 1:10 new2(3, 1) end
BenchmarkTools.Trial:
  memory estimate:  480 bytes
  allocs estimate:  20
  --------------
  minimum time:     342.917 ns (0.00% GC)
  median time:      352.157 ns (0.00% GC)
  mean time:        394.988 ns (7.70% GC)
  maximum time:     8.064 μs (92.64% GC)
  --------------
  samples:          10000
  evals/sample:     216
```
So if the error condition isn't triggered, `Union`s are actually _worse_ than `try` on 0.6.

We should probably just forget about this until you're ready to drop 0.6 support. Since this package changes so infrequently and its API remains the same after this change, I'd personally say going 0.7/1.0 only at this point would make sense, as it allows dropping dependencies on both Compat and Nullables. But of course it's completely up to you.

**Comment by ararslan** [comment]
Just for fun, I tried another variation using `Union{T, Exception}` in place of `Result{T, Exception}` and found that it too results in equivalent performance on 1.0:
```
julia> t4 = @benchmark for i = 1:10 new3(3, i % 2) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.827 ns (0.00% GC)
  median time:      1.980 ns (0.00% GC)
  mean time:        2.016 ns (0.00% GC)
  maximum time:     33.538 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

julia> t4 = @benchmark for i = 1:10 new3(3, 1) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.827 ns (0.00% GC)
  median time:      1.978 ns (0.00% GC)
  mean time:        1.996 ns (0.00% GC)
  maximum time:     27.236 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
```
Amusingly, on 0.6 this actually seems to be the worst possible option:
```
julia> t4 = @benchmark for i = 1:10 new3(3, i % 2) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     443.455 ns (0.00% GC)
  median time:      444.328 ns (0.00% GC)
  mean time:        456.379 ns (0.00% GC)
  maximum time:     1.146 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     198

julia> t4 = @benchmark for i = 1:10 new3(3, 1) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     494.747 ns (0.00% GC)
  median time:      498.247 ns (0.00% GC)
  mean time:        509.827 ns (0.00% GC)
  maximum time:     1.202 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     194
```

**Comment by iamed2** [comment]
Can you put `for i = 1:10 new1(3, i % 2)` in a function and do `code_llvm`? the <2 ns seems suspicious, like it's eliminating too much code for the benchmark to be valid.

**Comment by ararslan** [comment]
With `Nullable`:
```llvm
; Function thing1
; Location: /Users/alex/Projects/testing/compare.jl:43
define nonnull %jl_value_t addrspace(10)* @japi1_thing1_36113(%jl_value_t addrspace(10)*, %jl_value_t addrspace(10)**, i32) #0 {
top:
  %3 = alloca %jl_value_t addrspace(10)**, align 8
  store volatile %jl_value_t addrspace(10)** %1, %jl_value_t addrspace(10)*** %3, align 8
; Location: /Users/alex/Projects/testing/compare.jl:44
  ret %jl_value_t addrspace(10)* addrspacecast (%jl_value_t* inttoptr (i64 4454752264 to %jl_value_t*) to %jl_value_t addrspace(10)*)
}
```
With `Union`:
```llvm
; Function thing2
; Location: /Users/alex/Projects/testing/compare.jl:43
define nonnull %jl_value_t addrspace(10)* @japi1_thing2_36114(%jl_value_t addrspace(10)*, %jl_value_t addrspace(10)**, i32) #0 {
top:
  %3 = alloca %jl_value_t addrspace(10)**, align 8
  store volatile %jl_value_t addrspace(10)** %1, %jl_value_t addrspace(10)*** %3, align 8
; Location: /Users/alex/Projects/testing/compare.jl:44
  ret %jl_value_t addrspace(10)* addrspacecast (%jl_value_t* inttoptr (i64 4454752264 to %jl_value_t*) to %jl_value_t addrspace(10)*)
}
```
Exact same generated code. And with `func1`:
```llvm
; Function thing0
; Location: REPL[2]:2
define nonnull %jl_value_t addrspace(10)* @japi1_thing0_36126(%jl_value_t addrspace(10)*, %jl_value_t addrspace(10)**, i32) #0 {
top:
  %3 = alloca %jl_value_t addrspace(10)**, align 8
  store volatile %jl_value_t addrspace(10)** %1, %jl_value_t addrspace(10)*** %3, align 8
; Location: REPL[2]:3
  %4 = call i64 @julia_func1_35984(i64 3, i64 1)
  %5 = call i64 @julia_func1_35984(i64 3, i64 0)
  %6 = call i64 @julia_func1_35984(i64 3, i64 1)
  %7 = call i64 @julia_func1_35984(i64 3, i64 0)
  %8 = call i64 @julia_func1_35984(i64 3, i64 1)
  %9 = call i64 @julia_func1_35984(i64 3, i64 0)
  %10 = call i64 @julia_func1_35984(i64 3, i64 1)
  %11 = call i64 @julia_func1_35984(i64 3, i64 0)
  %12 = call i64 @julia_func1_35984(i64 3, i64 1)
  %13 = call i64 @julia_func1_35984(i64 3, i64 0)
  ret %jl_value_t addrspace(10)* addrspacecast (%jl_value_t* inttoptr (i64 4454752264 to %jl_value_t*) to %jl_value_t addrspace(10)*)
}
```

**Comment by iamed2** [comment]
Yup, those are not actually running anything, that's why they're <2 ns. Gotta `@noinline` or something.

**Comment by ararslan** [comment]
Okay, I added `@noinline` to the `newX` definitions and we still get the same generated code, but it's no longer eliminating everything.

`Nullable`:
```llvm
; Function thing1
; Location: /Users/alex/Projects/testing/compare.jl:43
define nonnull %jl_value_t addrspace(10)* @japi1_thing1_36120(%jl_value_t addrspace(10)*, %jl_value_t addrspace(10)**, i32) #0 {
top:
  %3 = alloca %jl_value_t addrspace(10)**, align 8
  store volatile %jl_value_t addrspace(10)** %1, %jl_value_t addrspace(10)*** %3, align 8
; Location: /Users/alex/Projects/testing/compare.jl:44
  %4 = call i64 @julia_new1_36031(i64 3, i64 1)
  %5 = call i64 @julia_new1_36031(i64 3, i64 0)
  %6 = call i64 @julia_new1_36031(i64 3, i64 1)
  %7 = call i64 @julia_new1_36031(i64 3, i64 0)
  %8 = call i64 @julia_new1_36031(i64 3, i64 1)
  %9 = call i64 @julia_new1_36031(i64 3, i64 0)
  %10 = call i64 @julia_new1_36031(i64 3, i64 1)
  %11 = call i64 @julia_new1_36031(i64 3, i64 0)
  %12 = call i64 @julia_new1_36031(i64 3, i64 1)
  %13 = call i64 @julia_new1_36031(i64 3, i64 0)
  ret %jl_value_t addrspace(10)* addrspacecast (%jl_value_t* inttoptr (i64 4627591176 to %jl_value_t*) to %jl_value_t addrspace(10)*)
}
```
`Union`:
```llvm
; Function thing2
; Location: /Users/alex/Projects/testing/compare.jl:43
define nonnull %jl_value_t addrspace(10)* @japi1_thing2_36121(%jl_value_t addrspace(10)*, %jl_value_t addrspace(10)**, i32) #0 {
top:
  %3 = alloca %jl_value_t addrspace(10)**, align 8
  store volatile %jl_value_t addrspace(10)** %1, %jl_value_t addrspace(10)*** %3, align 8
; Location: /Users/alex/Projects/testing/compare.jl:44
  %4 = call i64 @julia_new2_36047(i64 3, i64 1)
  %5 = call i64 @julia_new2_36047(i64 3, i64 0)
  %6 = call i64 @julia_new2_36047(i64 3, i64 1)
  %7 = call i64 @julia_new2_36047(i64 3, i64 0)
  %8 = call i64 @julia_new2_36047(i64 3, i64 1)
  %9 = call i64 @julia_new2_36047(i64 3, i64 0)
  %10 = call i64 @julia_new2_36047(i64 3, i64 1)
  %11 = call i64 @julia_new2_36047(i64 3, i64 0)
  %12 = call i64 @julia_new2_36047(i64 3, i64 1)
  %13 = call i64 @julia_new2_36047(i64 3, i64 0)
  ret %jl_value_t addrspace(10)* addrspacecast (%jl_value_t* inttoptr (i64 4627591176 to %jl_value_t*) to %jl_value_t addrspace(10)*)
}
```

**Comment by iamed2** [comment]
Hooray! But now you have to run the benchmarks again.

**Comment by ararslan** [comment]
Average case:
```
julia> t1 = @benchmark for i = 1:10 func1(3, i % 2) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     138.723 μs (0.00% GC)
  median time:      141.050 μs (0.00% GC)
  mean time:        146.596 μs (0.00% GC)
  maximum time:     942.764 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

julia> t2 = @benchmark for i = 1:10 new1(3, i % 2) end # Nullable
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     24.945 ns (0.00% GC)
  median time:      27.195 ns (0.00% GC)
  mean time:        27.840 ns (0.00% GC)
  maximum time:     387.043 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     994

julia> t3 = @benchmark for i = 1:10 new2(3, i % 2) end # Union
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     24.598 ns (0.00% GC)
  median time:      26.414 ns (0.00% GC)
  mean time:        27.363 ns (0.00% GC)
  maximum time:     123.967 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     995
```
No error:
```
julia> n1 = @benchmark for i = 1:10 func1(3, 1) end
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     170.608 ns (0.00% GC)
  median time:      172.262 ns (0.00% GC)
  mean time:        175.586 ns (0.00% GC)
  maximum time:     778.853 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     737

julia> n2 = @benchmark for i = 1:10 new1(3, 1) end # Nullable
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     34.666 ns (0.00% GC)
  median time:      34.837 ns (0.00% GC)
  mean time:        35.519 ns (0.00% GC)
  maximum time:     98.555 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     992

julia> n3 = @benchmark for i = 1:10 new2(3, 1) end # Union
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     34.964 ns (0.00% GC)
  median time:      35.317 ns (0.00% GC)
  mean time:        36.038 ns (0.00% GC)
  maximum time:     122.291 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     992
```

**Comment by iamed2** [comment]
Alright that's the good stuff

**Comment by iamed2** [comment]
Since there were no API changes I'd be ok merging this with a minimum Julia version of 0.7. Just gotta fix the Travis config conflicts.

Also update the benchmark numbers/comments in the README

**Comment by ararslan** [comment]
I also need to update the constructor vs. convert thingamajig

**Comment by ararslan** [comment]
I think we're all good here now.

**Review by iamed2 — APPROVED** [review]

**Pull request merged**
