### PR TITLE
Update to new package format

### PR DESCRIPTION
**Pull request by kmsquire**
This is essentially what is produced by the current (released) version of PkgTemplates.jl

### CODE REVIEW

**Review by iamed2 — APPROVED** [review]

**Comment by kmsquire** [comment]
Looks like `Documenter` couldn't push the docs: https://travis-ci.org/iamed2/ResultTypes.jl/jobs/652121316#L317-L326

**Comment by iamed2** [comment]
Strange, I have a `DOCUMENTER_KEY` variable set on Travis but no key in the repo config...

I'll regenerate the key.

**Comment by iamed2** [comment]
Docs now updated

**Comment by kmsquire** [comment]
Thanks!

**Pull request merged**
